# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200306_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='系列的名称')),
                ('articles', models.ManyToManyField(to='app01.Article', verbose_name='文章')),
            ],
        ),
        migrations.CreateModel(
            name='UserSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(default='0.00', max_length=32)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Series', verbose_name='系列')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='users',
            field=models.ManyToManyField(through='app01.UserSeries', to='app01.User', verbose_name='用户'),
        ),
    ]
