# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200310_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='article',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='users',
            field=models.ManyToManyField(related_name='series', through='app01.UserSeries', to='app01.User', verbose_name='用户'),
        ),
    ]
