# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200310_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='推荐阅读时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='point',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='pointdetail',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Article', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='pointdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='用户'),
        ),
    ]
