# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_pointdetail_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseries',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userseries',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
