# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200302_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, choices=[('0', '北京总公司'), ('1', '石家庄分公司'), ('2', '广州分公司')], max_length=32, verbose_name='公司'),
        ),
    ]
