# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200305_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/avatar/dafault.jpeg', upload_to='img/avatar'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=256, verbose_name='文章摘要'),
        ),
    ]
