# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '所有用户信息'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
