# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200303_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
